
import type { Territory } from "@/types";

/**
 * 24 territories of the biblical ancient Near East.
 * Blocked territories cannot be selected as starting territories.
 */
export const TERRITORIES: Territory[] = [
  // ── Egito ─────────────────────────────────────────────────────────────────
  {
    id: "egito",
    name: "Egito",
    regionId: "egypt",
    type: "capital",
    position: { x: 180, y: 560 },
    connections: ["gosen", "sinai", "deserto_sur"],
    defesaNatural: 4,
    feBase: 15,
    feAtual: 15,
    tropasNeutrasIniciais: 5,
    tropasAtuais: 5,
    donoAtual: null,
    estado: "neutro",
    bloqueado: true,
    producao: { provisao: 4, ouro: 3, influencia: 2 },
    melhorias: [],
    pontoForte: "Alta produção e defesa natural do Nilo",
    pontoFraco: "Fé baixa — povo idólatra",
    descricao: "O maior império do mundo antigo. Governado pelo Faraó, opressor de Israel.",
  },
  {
    id: "gosen",
    name: "Gósen",
    regionId: "egypt",
    type: "comum",
    position: { x: 250, y: 500 },
    connections: ["egito", "sinai", "deserto_sur"],
    defesaNatural: 2,
    feBase: 55,
    feAtual: 55,
    tropasNeutrasIniciais: 2,
    tropasAtuais: 2,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 3, ouro: 1, influencia: 1 },
    melhorias: [],
    pontoForte: "Terra fértil do delta do Nilo, rica em alimentos",
    pontoFraco: "Sem defesas naturais expressivas",
    descricao: "A terra onde os filhos de Israel viveram como servos. Solo fértil e memória do êxodo.",
  },
  {
    id: "sinai",
    name: "Sinai",
    regionId: "egypt",
    type: "sagrado",
    position: { x: 310, y: 570 },
    connections: ["egito", "gosen", "deserto_sur", "neguebe"],
    defesaNatural: 2,
    feBase: 80,
    feAtual: 80,
    tropasNeutrasIniciais: 1,
    tropasAtuais: 1,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 1, ouro: 0, influencia: 3 },
    melhorias: [],
    pontoForte: "Fé muito alta — lugar da aliança com Deus",
    pontoFraco: "Sem produção de ouro, isolado",
    descricao: "O monte onde Moisés recebeu a Lei. Lugar sagrado e de revelação divina.",
  },
  {
    id: "deserto_sur",
    name: "Deserto de Sur",
    regionId: "egypt",
    type: "comum",
    position: { x: 290, y: 490 },
    connections: ["egito", "gosen", "sinai", "neguebe", "gaza"],
    defesaNatural: 1,
    feBase: 35,
    feAtual: 35,
    tropasNeutrasIniciais: 1,
    tropasAtuais: 1,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 1, ouro: 0, influencia: 0 },
    melhorias: [],
    pontoForte: "Rota de passagem entre Egito e Canaã",
    pontoFraco: "Terra árida, produção mínima",
    descricao: "O deserto percorrido por Israel após o Êxodo. Árido e sem recursos.",
  },

  // ── Canaã / Judá ──────────────────────────────────────────────────────────
  {
    id: "hebrom",
    name: "Hebrom",
    regionId: "canaa",
    type: "sagrado",
    position: { x: 390, y: 430 },
    connections: ["neguebe", "belem", "jerusalem", "edom"],
    defesaNatural: 3,
    feBase: 70,
    feAtual: 70,
    tropasNeutrasIniciais: 2,
    tropasAtuais: 2,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 2, ouro: 1, influencia: 2 },
    melhorias: [],
    pontoForte: "Cidade dos patriarcas — Abraão, Isaque e Jacó",
    pontoFraco: "Cercada por inimigos ao sul",
    descricao: "Onde Abraão habitou e onde os patriarcas estão sepultados. Cidade de grande valor espiritual.",
  },
  {
    id: "jerusalem",
    name: "Jerusalém",
    regionId: "canaa",
    type: "capital",
    position: { x: 420, y: 380 },
    connections: ["hebrom", "belem", "jerico", "filistia"],
    defesaNatural: 5,
    feBase: 95,
    feAtual: 95,
    tropasNeutrasIniciais: 6,
    tropasAtuais: 6,
    donoAtual: null,
    estado: "neutro",
    bloqueado: true,
    producao: { provisao: 2, ouro: 3, influencia: 4 },
    melhorias: [],
    pontoForte: "Alta fé, alta influência, defesa máxima",
    pontoFraco: "Disputada por todas as facções",
    descricao: "A Cidade Santa. Capital do reino de Davi e Salomão. Quem a controla domina o coração de Canaã.",
  },
  {
    id: "belem",
    name: "Belém",
    regionId: "canaa",
    type: "sagrado",
    position: { x: 410, y: 400 },
    connections: ["hebrom", "jerusalem", "neguebe", "filistia"],
    defesaNatural: 2,
    feBase: 75,
    feAtual: 75,
    tropasNeutrasIniciais: 2,
    tropasAtuais: 2,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 2, ouro: 1, influencia: 2 },
    melhorias: [],
    pontoForte: "Cidade de Davi, forte ligação espiritual",
    pontoFraco: "Sem defesas naturais",
    descricao: "Terra natal de Davi e Rute. Cidade de colheitas e esperança.",
  },
  {
    id: "neguebe",
    name: "Neguebe",
    regionId: "canaa",
    type: "comum",
    position: { x: 370, y: 470 },
    connections: ["hebrom", "belem", "gaza", "sinai", "deserto_sur", "edom"],
    defesaNatural: 2,
    feBase: 40,
    feAtual: 40,
    tropasNeutrasIniciais: 1,
    tropasAtuais: 1,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 2, ouro: 1, influencia: 0 },
    melhorias: [],
    pontoForte: "Rota de comércio sul-norte",
    pontoFraco: "Terra semiárida, vulnerável",
    descricao: "O sul de Canaã. Ponto de passagem entre Canaã e Egito. Pastagens e travessias.",
  },
  {
    id: "jerico",
    name: "Jericó",
    regionId: "canaa",
    type: "estrategico",
    position: { x: 460, y: 350 },
    connections: ["jerusalem", "siquem", "amom", "gileade"],
    defesaNatural: 4,
    feBase: 50,
    feAtual: 50,
    tropasNeutrasIniciais: 5,
    tropasAtuais: 5,
    donoAtual: null,
    estado: "neutro",
    bloqueado: true,
    producao: { provisao: 2, ouro: 2, influencia: 1 },
    melhorias: [],
    pontoForte: "Portão de Canaã — posição estratégica",
    pontoFraco: "Queda das muralhas — histórico de colapso",
    descricao: "A primeira cidade conquistada por Josué. Guarda a entrada de Canaã pelo Jordão.",
  },

  // ── Israel Norte ──────────────────────────────────────────────────────────
  {
    id: "siquem",
    name: "Siquém",
    regionId: "israel_norte",
    type: "estrategico",
    position: { x: 440, y: 300 },
    connections: ["jerico", "samaria", "gileade"],
    defesaNatural: 2,
    feBase: 45,
    feAtual: 45,
    tropasNeutrasIniciais: 2,
    tropasAtuais: 2,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 2, ouro: 1, influencia: 1 },
    melhorias: [],
    pontoForte: "Ponto central de rotas norte-sul",
    pontoFraco: "Instabilidade tribal constante",
    descricao: "Cidade onde Abraão construiu seu primeiro altar. Local de assembleias tribais de Israel.",
  },
  {
    id: "samaria",
    name: "Samaria",
    regionId: "israel_norte",
    type: "capital",
    position: { x: 430, y: 260 },
    connections: ["siquem", "megido", "filistia"],
    defesaNatural: 3,
    feBase: 30,
    feAtual: 30,
    tropasNeutrasIniciais: 3,
    tropasAtuais: 3,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 2, ouro: 2, influencia: 2 },
    melhorias: [],
    pontoForte: "Capital do Reino do Norte — alto ouro",
    pontoFraco: "Fé baixa — sincretismo e idolatria",
    descricao: "Capital do reino de Israel do Norte. Construída por Onri, palco da apostasia e dos profetas.",
  },
  {
    id: "megido",
    name: "Megido",
    regionId: "israel_norte",
    type: "estrategico",
    position: { x: 400, y: 220 },
    connections: ["samaria", "tiro", "sidom", "damasco"],
    defesaNatural: 3,
    feBase: 40,
    feAtual: 40,
    tropasNeutrasIniciais: 3,
    tropasAtuais: 3,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 1, ouro: 2, influencia: 2 },
    melhorias: [],
    pontoForte: "Posição estratégica — controla rotas norte",
    pontoFraco: "Historicamente palco de batalhas devastadoras",
    descricao: "Armagedom. Rota militar entre Egito, Fenícia e Mesopotâmia. Local de batalhas decisivas.",
  },

  // ── Costa / Fenícia / Filistia ─────────────────────────────────────────────
  {
    id: "filistia",
    name: "Filístia",
    regionId: "costa",
    type: "estrategico",
    position: { x: 355, y: 350 },
    connections: ["jerusalem", "belem", "gaza", "samaria"],
    defesaNatural: 3,
    feBase: 20,
    feAtual: 20,
    tropasNeutrasIniciais: 3,
    tropasAtuais: 3,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 1, ouro: 2, influencia: 2 },
    melhorias: [],
    pontoForte: "Guerreiros experientes, ferraria avançada",
    pontoFraco: "Inimigos históricos de Israel — baixa fé",
    descricao: "O povo do mar. Guerreiros de ferro que desafiaram Israel por gerações. Lar de Golias.",
  },
  {
    id: "gaza",
    name: "Gaza",
    regionId: "costa",
    type: "estrategico",
    position: { x: 320, y: 410 },
    connections: ["filistia", "neguebe", "deserto_sur"],
    defesaNatural: 3,
    feBase: 15,
    feAtual: 15,
    tropasNeutrasIniciais: 3,
    tropasAtuais: 3,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 2, ouro: 3, influencia: 1 },
    melhorias: [],
    pontoForte: "Porto com alto comércio, rota entre Egito e Canaã",
    pontoFraco: "Baixa fé — centro filisteu",
    descricao: "O porto dos Filisteus. Cidade onde Sansão morreu. Rico em comércio costeiro.",
  },
  {
    id: "tiro",
    name: "Tiro",
    regionId: "fenicia",
    type: "estrategico",
    position: { x: 355, y: 155 },
    connections: ["megido", "sidom", "damasco"],
    defesaNatural: 4,
    feBase: 25,
    feAtual: 25,
    tropasNeutrasIniciais: 3,
    tropasAtuais: 3,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 1, ouro: 4, influencia: 3 },
    melhorias: [],
    pontoForte: "Maior porto da antiguidade — ouro alto",
    pontoFraco: "Povo mercante sem fé no Deus de Israel",
    descricao: "A cidade insular dos Fenícios. Aliada de Salomão, forneceu cedro para o Templo.",
  },
  {
    id: "sidom",
    name: "Sidom",
    regionId: "fenicia",
    type: "comum",
    position: { x: 345, y: 115 },
    connections: ["tiro", "megido", "damasco"],
    defesaNatural: 3,
    feBase: 20,
    feAtual: 20,
    tropasNeutrasIniciais: 2,
    tropasAtuais: 2,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 1, ouro: 3, influencia: 2 },
    melhorias: [],
    pontoForte: "Cidade mãe da Fenícia, grande influência",
    pontoFraco: "Origem de Jezabel — centro de idolatria",
    descricao: "A cidade mais antiga da Fenícia. De lá vieram os comerciantes que espalharam seu culto a Baal.",
  },

  // ── Transjordânia ─────────────────────────────────────────────────────────
  {
    id: "moabe",
    name: "Moabe",
    regionId: "transjordania",
    type: "comum",
    position: { x: 490, y: 420 },
    connections: ["edom", "amom", "gileade", "hebrom"],
    defesaNatural: 2,
    feBase: 30,
    feAtual: 30,
    tropasNeutrasIniciais: 2,
    tropasAtuais: 2,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 2, ouro: 1, influencia: 1 },
    melhorias: [],
    pontoForte: "Aliança ocasional com Israel, pastagens",
    pontoFraco: "Idolatria — Quemós, deus de Moabe",
    descricao: "Terra dos descendentes de Ló. Rute era moabita. Inimiga e aliada alternada de Israel.",
  },
  {
    id: "edom",
    name: "Edom",
    regionId: "transjordania",
    type: "comum",
    position: { x: 460, y: 490 },
    connections: ["moabe", "neguebe", "hebrom"],
    defesaNatural: 3,
    feBase: 25,
    feAtual: 25,
    tropasNeutrasIniciais: 2,
    tropasAtuais: 2,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 1, ouro: 2, influencia: 1 },
    melhorias: [],
    pontoForte: "Rico em minérios e metais",
    pontoFraco: "Inimigo histórico de Israel — inimizade de Esaú",
    descricao: "A terra de Esaú. Sempre em conflito com Israel. Rica em recursos minerais nas montanhas.",
  },
  {
    id: "amom",
    name: "Amom",
    regionId: "transjordania",
    type: "comum",
    position: { x: 510, y: 360 },
    connections: ["jerico", "gileade", "moabe", "damasco"],
    defesaNatural: 2,
    feBase: 25,
    feAtual: 25,
    tropasNeutrasIniciais: 2,
    tropasAtuais: 2,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 2, ouro: 1, influencia: 1 },
    melhorias: [],
    pontoForte: "Posição estratégica entre Israel e Damasco",
    pontoFraco: "Culto a Moloque — conflito constante",
    descricao: "Os filhos de Amom, parentes de Israel. Rivais frequentes e motivo de guerras.",
  },
  {
    id: "gileade",
    name: "Gileade",
    regionId: "transjordania",
    type: "estrategico",
    position: { x: 500, y: 300 },
    connections: ["jerico", "siquem", "amom", "moabe", "damasco"],
    defesaNatural: 2,
    feBase: 50,
    feAtual: 50,
    tropasNeutrasIniciais: 2,
    tropasAtuais: 2,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 3, ouro: 1, influencia: 1 },
    melhorias: [],
    pontoForte: "Pastagens ricas e posição elevada",
    pontoFraco: "Fronteira exposta ao norte",
    descricao: "A região florestal a leste do Jordão. Lar de Jefté e Elias. Produtiva e estratégica.",
  },

  // ── Aram / Mesopotâmia ────────────────────────────────────────────────────
  {
    id: "damasco",
    name: "Damasco",
    regionId: "aram",
    type: "capital",
    position: { x: 520, y: 160 },
    connections: ["megido", "tiro", "sidom", "gileade", "amom", "ninive"],
    defesaNatural: 3,
    feBase: 20,
    feAtual: 20,
    tropasNeutrasIniciais: 4,
    tropasAtuais: 4,
    donoAtual: null,
    estado: "neutro",
    bloqueado: false,
    producao: { provisao: 2, ouro: 3, influencia: 3 },
    melhorias: [],
    pontoForte: "Centro das rotas comerciais do norte",
    pontoFraco: "Ameaça constante da Assíria",
    descricao: "A capital da Síria. Rival de Israel, aliada alternada. Centro de poder do norte.",
  },
  {
    id: "ninive",
    name: "Nínive",
    regionId: "mesopotamia",
    type: "capital",
    position: { x: 660, y: 120 },
    connections: ["damasco", "babilonia"],
    defesaNatural: 5,
    feBase: 10,
    feAtual: 10,
    tropasNeutrasIniciais: 7,
    tropasAtuais: 7,
    donoAtual: null,
    estado: "neutro",
    bloqueado: true,
    producao: { provisao: 3, ouro: 5, influencia: 4 },
    melhorias: [],
    pontoForte: "Maior exército da época, alta produção",
    pontoFraco: "Fé mínima — centro do paganismo assírio",
    descricao: "Capital da Assíria. Para onde Jonás foi enviado. O terror do mundo antigo.",
  },
  {
    id: "babilonia",
    name: "Babilônia",
    regionId: "mesopotamia",
    type: "capital",
    position: { x: 700, y: 240 },
    connections: ["ninive", "susa"],
    defesaNatural: 5,
    feBase: 10,
    feAtual: 10,
    tropasNeutrasIniciais: 7,
    tropasAtuais: 7,
    donoAtual: null,
    estado: "neutro",
    bloqueado: true,
    producao: { provisao: 3, ouro: 5, influencia: 5 },
    melhorias: [],
    pontoForte: "Enorme poder político e militar",
    pontoFraco: "Apostasia total — Belshazar e seus deuses",
    descricao: "O grande império que destruiu Jerusalém e levou Israel ao cativeiro. Torre de Babel, Jardins Suspensos.",
  },
  {
    id: "susa",
    name: "Susa / Pérsia",
    regionId: "mesopotamia",
    type: "capital",
    position: { x: 750, y: 330 },
    connections: ["babilonia"],
    defesaNatural: 4,
    feBase: 40,
    feAtual: 40,
    tropasNeutrasIniciais: 6,
    tropasAtuais: 6,
    donoAtual: null,
    estado: "neutro",
    bloqueado: true,
    producao: { provisao: 2, ouro: 4, influencia: 5 },
    melhorias: [],
    pontoForte: "Lar de Ester e Neemias — influência política",
    pontoFraco: "Distante das terras de Israel",
    descricao: "Capital da Pérsia. Onde Ester corajosamente intercedeu pelo povo. O império que permitiu o retorno.",
  },
];
