
import type { Territory } from "@/types";

/**
 * Static territory data for the Reinos & Promessas map.
 * Based on key regions of the ancient Near East / Old Testament world.
 */
export const TERRITORIES: Territory[] = [
  // ── Canaã / Israel ──────────────────────────────────────────────────────
  {
    id: "jerusalem",
    name: "Jerusalém",
    regionId: "judah",
    adjacentIds: ["hebron", "jerico", "samaria", "filistia_norte"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 2, faith: 2 },
    position: { x: 480, y: 340 },
  },
  {
    id: "hebron",
    name: "Hebrom",
    regionId: "judah",
    adjacentIds: ["jerusalem", "beersheba", "filistia_sul"],
    ownerId: null,
    armies: 0,
    resourceBonus: { food: 1 },
    position: { x: 450, y: 410 },
  },
  {
    id: "beersheba",
    name: "Berseba",
    regionId: "judah",
    adjacentIds: ["hebron", "negev", "filistia_sul"],
    ownerId: null,
    armies: 0,
    resourceBonus: { food: 1 },
    position: { x: 430, y: 480 },
  },
  {
    id: "jerico",
    name: "Jericó",
    regionId: "benjamin",
    adjacentIds: ["jerusalem", "samaria", "transjordania_norte"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 1 },
    position: { x: 520, y: 320 },
  },
  {
    id: "samaria",
    name: "Samaria",
    regionId: "israel_norte",
    adjacentIds: ["jerico", "jerusalem", "megido", "transjordania_norte"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 1, food: 1 },
    position: { x: 480, y: 250 },
  },
  {
    id: "megido",
    name: "Megido",
    regionId: "israel_norte",
    adjacentIds: ["samaria", "acre", "damasco"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 1 },
    position: { x: 450, y: 180 },
  },
  {
    id: "acre",
    name: "Acre",
    regionId: "fenicia",
    adjacentIds: ["megido", "tiro", "sidao"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 2 },
    position: { x: 410, y: 140 },
  },
  {
    id: "tiro",
    name: "Tiro",
    regionId: "fenicia",
    adjacentIds: ["acre", "sidao", "damasco"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 3 },
    position: { x: 390, y: 100 },
  },
  {
    id: "sidao",
    name: "Sidom",
    regionId: "fenicia",
    adjacentIds: ["tiro", "damasco"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 2 },
    position: { x: 370, y: 60 },
  },
  // ── Filistia ─────────────────────────────────────────────────────────────
  {
    id: "filistia_norte",
    name: "Jope",
    regionId: "filistia",
    adjacentIds: ["jerusalem", "filistia_sul", "megido"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 1 },
    position: { x: 390, y: 290 },
  },
  {
    id: "filistia_sul",
    name: "Gaza",
    regionId: "filistia",
    adjacentIds: ["filistia_norte", "hebron", "beersheba", "egito_norte"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 1, food: 1 },
    position: { x: 370, y: 390 },
  },
  // ── Egito ─────────────────────────────────────────────────────────────────
  {
    id: "egito_norte",
    name: "Mênfis",
    regionId: "egypt",
    adjacentIds: ["filistia_sul", "negev", "egito_sul"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 2, food: 2 },
    position: { x: 290, y: 470 },
  },
  {
    id: "egito_sul",
    name: "Tebas",
    regionId: "egypt",
    adjacentIds: ["egito_norte"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 1, food: 3 },
    position: { x: 260, y: 570 },
  },
  {
    id: "negev",
    name: "Neguebe",
    regionId: "judah",
    adjacentIds: ["beersheba", "egito_norte", "sinai"],
    ownerId: null,
    armies: 0,
    resourceBonus: {},
    position: { x: 400, y: 540 },
  },
  {
    id: "sinai",
    name: "Sinai",
    regionId: "desert",
    adjacentIds: ["negev", "egito_norte"],
    ownerId: null,
    armies: 0,
    resourceBonus: { faith: 1 },
    position: { x: 350, y: 600 },
  },
  // ── Transjordânia ─────────────────────────────────────────────────────────
  {
    id: "transjordania_norte",
    name: "Gileade",
    regionId: "transjordan",
    adjacentIds: ["jerico", "samaria", "damasco", "transjordania_sul"],
    ownerId: null,
    armies: 0,
    resourceBonus: { food: 2 },
    position: { x: 570, y: 270 },
  },
  {
    id: "transjordania_sul",
    name: "Moabe",
    regionId: "transjordan",
    adjacentIds: ["transjordania_norte", "edom"],
    ownerId: null,
    armies: 0,
    resourceBonus: { food: 1 },
    position: { x: 560, y: 380 },
  },
  {
    id: "edom",
    name: "Edom",
    regionId: "transjordan",
    adjacentIds: ["transjordania_sul", "beersheba"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 1 },
    position: { x: 530, y: 470 },
  },
  // ── Aram / Síria ──────────────────────────────────────────────────────────
  {
    id: "damasco",
    name: "Damasco",
    regionId: "aram",
    adjacentIds: ["megido", "tiro", "transjordania_norte", "hamate"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 2 },
    position: { x: 530, y: 130 },
  },
  {
    id: "hamate",
    name: "Hamate",
    regionId: "aram",
    adjacentIds: ["damasco", "assíria"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 1 },
    position: { x: 580, y: 60 },
  },
  // ── Assíria / Babilônia ───────────────────────────────────────────────────
  {
    id: "assíria",
    name: "Nínive",
    regionId: "assyria",
    adjacentIds: ["hamate", "babilonia"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 3 },
    position: { x: 680, y: 80 },
  },
  {
    id: "babilonia",
    name: "Babilônia",
    regionId: "babylon",
    adjacentIds: ["assíria"],
    ownerId: null,
    armies: 0,
    resourceBonus: { gold: 3, food: 1 },
    position: { x: 720, y: 200 },
  },
];
